version: '2'
services:

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always

  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "10000:8069"
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL= admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD= 123456
    restart: unless-stopped

volumes:
  db:
  web:
